import { registerSheet } from 'react-native-actions-sheet';
import CreateEntitiesSheet from './CreateEntitiesSheet';
import WorkOrderDetailsSheet from './WorkOrderDetailsSheet';
import AssetDetailsSheet from './AssetDetailsSheet';
import LocationDetailsSheet from './LocationDetailsSheet';
import CustomerDetailsSheet from './CustomerDetailsSheet';
import TeamDetailsSheet from './TeamDetailsSheet';
import UploadFileSheet from './UploadFileSheet';
import BasicSelectSheet from './BasicSelectSheet';
import DropDownSheet from './DropDownSheet';

registerSheet('create-entities-sheet', CreateEntitiesSheet);
registerSheet('work-order-details-sheet', WorkOrderDetailsSheet);
registerSheet('asset-details-sheet', AssetDetailsSheet);
registerSheet('location-details-sheet', LocationDetailsSheet);
registerSheet('customer-details-sheet', CustomerDetailsSheet);
registerSheet('team-details-sheet', TeamDetailsSheet);
registerSheet('upload-file-sheet', UploadFileSheet);
registerSheet('basic-select-sheet', BasicSelectSheet);
registerSheet('dropdown-sheet', DropDownSheet);
export {};
